!define BG_MAIN_COLOR      #66BCF0
!define BG_SECONDARY_COLOR #B4BCBE
!define BG_PACKAGE_COLOR   #eeb291
!define BORDER_COLOR       #444444
!define FONT_COLOR         #444444

skinparam backgroundColor #white

' include the general skinparams for both, light and dark
' to overwrite with the given settings
!include general.puml

skinparam state {
    BackgroundColor #ade8f4
    FontColor #03045e
    AttributeFontColor #03045e
    ArrowColor #023e8a
    BorderColor #0077b6
}

skinparam class {
    BackgroundColor #ade8f4
}

skinparam arrowThickness 1

